spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: energy-usage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


simulation:
  fixedDelay: 5000
  requests-per-interval: 1500
  parallel-threads: 8
  endpoint: http://localhost:8082/api/v1/ingestion


server:
  port: 8082