spring:
  application:
    name: usage-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: energyUsageEvent:com.neeraj.kafka.event.EnergyUsageEvent
    template:
      default-topic: energy-alerts
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

influxdb:
  url: http://localhost:8072
  token: my-token
  org: neeraj
  bucket: usage-bucket

device:
  service:
    url: http://localhost:8081

user:
  service:
    url: http://localhost:8080

server:
  port: 8083
